#pragma once

const char *g_city_list[] = {"New Haven",
                             "Louisville",
                             "Los Angeles",
                             "Detroit",
                             "Lowell",
                             "Grand Prairie",
                             "San Antonio, Texas",
                             "Murfreesboro, Tennessee",
                             "Costa Mesa",
                             "Providence, Rhode Island",
                             "Lubbock",
                             "Brownsville",
                             "Ontario",
                             "Tacoma, Washington",
                             "Seattle",
                             "Pittsburgh, Pennsylvania",
                             "Gilbert",
                             "South Bend, Indiana",
                             "Santa Rosa, California",
                             "Akron",
                             "Plano, Texas",
                             "Allentown",
                             "Pago Pago, American Samoa",
                             "Coral Springs",
                             "Madison",
                             "Eugene",
                             "Green Bay",
                             "Fontana",
                             "Hayward",
                             "Columbia, South Carolina",
                             "Memphis, Tennessee",
                             "Jersey City",
                             "Vancouver",
                             "Glendale, Arizona",
                             "Buffalo",
                             "Houston",
                             "Garland",
                             "Springfield, Illinois",
                             "Pomona, California",
                             "Oxnard",
                             "Anaheim",
                             "Laredo",
                             "Little Rock",
                             "Montgomery, Alabama",
                             "Simi Valley, California",
                             "Vallejo",
                             "Lakewood",
                             "Columbia, Missouri",
                             "Huntington Beach",
                             "Columbus, Ohio",
                             "Sacramento, California",
                             "Mesa, Arizona",
                             "Norwalk",
                             "St Louis, Missouri",
                             "Orlando",
                             "Boise",
                             "St Paul, Minnesota",
                             "Tampa, Florida",
                             "Riverside",
                             "Charlotte",
                             "West Valley City, Utah",
                             "Washington, D.C.",
                             "Cambridge",
                             "Richmond",
                             "Salem, Oregon",
                             "Denver",
                             "Thousand Oaks, California",
                             "Fullerton",
                             "Raleigh",
                             "Chattanooga",
                             "Elk Grove",
                             "Davenport",
                             "Jacksonville",
                             "Springfield, Missouri",
                             "Lexington",
                             "Irvine",
                             "Watertown",
                             "Clarksville",
                             "El Monte",
                             "Corona",
                             "Indianapolis",
                             "Manchester, New Hampshire",
                             "Erie",
                             "Knoxville",
                             "Concord",
                             "Long Beach",
                             "Cedar Rapids",
                             "Berkeley",
                             "Las Vegas",
                             "Chula Vista",
                             "New York",
                             "Miami, Florida",
                             "Modesto, California",
                             "Phoenix, Arizona",
                             "Oklahoma City",
                             "Sunnyvale, California",
                             "Salt Lake City, Utah",
                             "Bellevue",
                             "Provo, Utah",
                             "Pembroke Pines, Florida"};
